# Generated by Django 6.1.1 on 2026-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(help_text='OPIS truckstop ID.', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(help_text='Highway/exit description.', max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(help_text='US state or Canadian province code.', max_length=2)),
                ('rack_id', models.PositiveIntegerField(help_text='OPIS wholesale pricing region.')),
                ('price', models.DecimalField(decimal_places=8, help_text='Retail price per gallon.', max_digits=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_precision', models.CharField(blank=True, choices=[('poi', 'Exact place found by name'), ('city', "Centre of the station's city")], default='', max_length=4)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='station_coords_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='station_price_positive'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='station_coords_set_together'), models.CheckConstraint(condition=models.Q(('latitude__isnull', True), ('latitude__range', (-90, 90)), _connector='OR'), name='station_latitude_in_range'), models.CheckConstraint(condition=models.Q(('longitude__isnull', True), ('longitude__range', (-180, 180)), _connector='OR'), name='station_longitude_in_range')],
            },
        ),
    ]
