# Generated by Django 6.1.1 on 2026-10-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='station',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('location_precision', '')), models.Q(('latitude__isnull', False), models.Q(('location_precision', ''), _negated=True)), _connector='OR'), name='station_precision_matches_coords'),
        ),
    ]
