# Generated by Django 6.1.1 on 2026-10-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_require_precision_with_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='location_precision',
            field=models.CharField(blank=True, choices=[('poi', 'Exact place found by name, used by this station alone'), ('city', "Approximate: somewhere in the station's city")], default='', max_length=4),
        ),
    ]
